[build]
  command = "node generate-static.mjs && npx esbuild fonts.css --bundle --outfile=fonts-local.css --minify --loader:.woff2=file --asset-names=fonts/[name]-[hash] && npx esbuild app.jsx --bundle --format=iife --platform=browser --target=es2018 --jsx=transform --outfile=app.js --minify"
  publish = "."
